name: E2E tests running in AWS Device Farm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          NETLIFY_DEPLOY_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          yarn tsc --build && yarn workspace @perf-profiler/web-reporter build
          npx link-lerna-package-binaries
          yarn test:e2e
          npx @perf-profiler/web-reporter report -o report
          ./.github/workflows/netlify-report.sh
      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## Flashlight Report 🔦

            - [🚀 Report](${{ env.NETLIFY_PREVIEW_URL }})
            - [📱 (Private) Test run](${{ env.AWS_CONSOLE_TEST_RUN_URL }})
